name: CI/CD Pipeline

on:
  #   push:
  #     branches:
  #       - main
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Build
        run: echo "Building the project..."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Application
        run: echo "Deploying the application..."
